# Project
version=1.0.9+1.21.1
group=com.illusivesoulworks.polymorph
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Polymorph
mod_author=Illusive Soulworks
mod_id=polymorph
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/polymorph/issues
sources_url=https://github.com/illusivesoulworks/polymorph
description=No more recipe conflicts! Adds an option to choose the crafting result if more than one is available.
minecraft_version_range=[1.21, 1.22)
minecraft_version_range_alt=~1.21

# Parchment
parchment_mc=1.21
parchment_version=2024.07.28

# Forge
forge_version=52.0.1
forge_version_range=[51,)

# Integrations
fastworkbench_version=1.21-9.1.1
placebo_version=1.21-9.3.4
emi_version=1.1.7+1.21
jei_version=19.0.0.11
rei_version=16.0.729

# NeoForge
neoforge_version=21.1.8
neoforge_version_range=[21.0.67,)

# Fabric
fabric_version=0.103.0+1.21.1
fabric_loader_version=0.15.11
cca_version=6.1.0

# CurseForge Options
cf_id=388800
cf_page=https://www.curseforge.com/minecraft/mc-mods/polymorph
modrinth_id=tagwiZkJ
modrinth_page=https://modrinth.com/mod/polymorph
release_type=release
release_versions=1.21.1,1.21
changelog_link=https://github.com/illusivesoulworks/polymorph/blob/1.21.x/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/279/271/637277042531842540.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
